# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:
  relayer1:
    container_name: relayer1-proxy
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile.bridge
    command:
      run --config /cfg/config_evm-evm_1.json --latest
    volumes:
      - ./cfg/:/cfg
    restart: always
    environment:
      - http_proxy=socks5://K2b7xpcdHbiKRIj:Du5c0PFEyjXb8ev@193.151.180.158:58684
      - https_proxy=socks5://K2b7xpcdHbiKRIj:Du5c0PFEyjXb8ev@193.151.180.158:58684

  relayer2:
    container_name: relayer2-proxy
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile.bridge
    command:
      run --config /cfg/config_evm-evm_2.json --latest
    volumes:
      - ./cfg/:/cfg
    restart: always
    environment:
      - http_proxy=socks5://K2b7xpcdHbiKRIj:Du5c0PFEyjXb8ev@193.151.180.158:58684
      - https_proxy=socks5://K2b7xpcdHbiKRIj:Du5c0PFEyjXb8ev@193.151.180.158:58684

  relayer3:
    container_name: relayer3-proxy
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile.bridge
    command:
      run --config /cfg/config_evm-evm_3.json --latest
    volumes:
      - ./cfg/:/cfg
    restart: always
    environment:
      - http_proxy=socks5://K2b7xpcdHbiKRIj:Du5c0PFEyjXb8ev@193.151.180.158:58684
      - https_proxy=socks5://K2b7xpcdHbiKRIj:Du5c0PFEyjXb8ev@193.151.180.158:58684

  # otel-collector:
  #   container_name: otel-collector
  #   image: otel/opentelemetry-collector
  #   command: ["--config=/etc/otel-collector-config.yml"]
  #   volumes:
  #     - ./cfg/otel-collector-config.yml:/etc/otel-collector-config.yml
  #   ports:
  #     - "8889:8889"   # Prometheus exporter metrics
