# Use a lightweight base image
FROM alpine:latest

# Install Dante and dependencies
RUN apk update && \
    apk add --no-cache dante-server

# Copy the configuration file
COPY ./docker/config/danted.conf /etc/danted.conf

# Expose the SOCKS proxy port
EXPOSE 1080

# Start the Dante service
CMD ["sockd", "-D"]
